
services:
  ros-master:
    image: ros-noetic-master
    container_name: ros-noetic-master
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    network_mode: "host"
    # command: bash -c "source /opt/ros/noetic/setup.bash && roscore"
    environment:
      - DISPLAY=:0
      - LIBGL_ALWAYS_SOFTWARE=1
      - QT_X11_NO_MITSHM=1
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
